sudo: false
language: ruby
rvm:
- 2.3.1
branches:
  only:
    - master
    - qa
    - develop
before_install:
  - export TRAVIS_BUILD_ENV="dev"
  - if [[ $TRAVIS_BRANCH = 'qa' ]]; then export TRAVIS_BUILD_ENV="qa"; fi
  - if [[ TRAVIS_BRANCH = 'master' ]]; then export TRAVIS_BUILD_ENV="prod"; fi
install:
- echo "$TRAVIS_BUILD_ENV"
- bundle install
- gem install jekyll
script:
- bundle exec jekyll build --config _config.yml,_config_"$TRAVIS_BUILD_ENV".yml
deploy:
  - provider: firebase
    token:
      secure: "xVGjP4fGLUUBzVZGyF7wWvSdGqrZ4hgAayfNHFKOHj6KbDqqC/04TsgJiOQmEUL2HMDvAvHV2in8T9PyL9MmqkF6kb8YEzZOKQcuG/qIwC+qIGOfm2CAKR6bN47BYUJUQN4Yf7rZ7/cWtRTRq2VsmVz34YLdwjxr442rFm/OGlCjYJh40lGMe6Wi0/Sn4JVNMKiP3WxUMUFcOtrIeRkq7L+55wZpvWCWCr8gS3+Z/J2PlPpCSYVrddJlFa7mVWitfGyzAMB8rS3gZ3OGC99+Afu4C1+FHeZHuh9bNgUm3bBYTfd4yvN1p02U82oL06wCVEjDMvWE57O5/QuO23a+JRHHnWhpJlBgMOLNOj/MAE555bm/Pqa/w8UuH4ff3uYL+PCXTZOWC2kQuDSvwRIa4MKdpcnBXIBg9rqkdN+Th0Eg+6BrHWmbyu55YGW/Zkcz1W4+xF1BS/frl2TAEOL2J4Oop4uX0H4NB037gBGzBgW7J8bcjeUP2k3UC/gDH+VcQx7oDTsaFTSgpseC4cJUSHLgTmTJacymzVv16YjaTcHoSm2E5riVj9dmll+VSSmoUpKKO9nRRhivHPRtMYQy0Y/xjoXbVVoTE5s9OLjJ9jveZW/pfG7xL1vdcLEB7x8UBPmx6/kvsSp3qe1zfK2oyU1XbQqtABKTRN57mD9p6BY="
    project: "dev.ezbc.me"
    on:
      branch: "develop"
  - provider: firebase
    token:
      secure: "ZlPJxKk7T0OTVygtpNfn3Z6/E5NHfMNktoJCQdTwEiL0oKW6t9m/IFJLwonPPzljHwTdcmBC0ugebkEpCVmAhVg9859Jv6zUldr6BiWj5SP9Z39cQHx47a52n/1GQCh3tfD+MPVDeEeTi33sWVTnHnvhXfvxirw/jtVsa8iAutRWHJiMg74j9pGfGggPkMPPoItGpj3QUlUG/xNEpIBI7OdGc9Fr7+ARnpRuqoAeDCNx+rsaYtlAWvD2yyitNMvn3W+mHMJJ7WHnehmb5VfpmwFHDg1Eq+aLE2OEmFls6IxJ0cQWZ+HnJYPFE/cxlW3aBeyGyaO5AKeMkHgIWom4hZzT2Fuxkke7UMLe6HEOI7+DmVPfFK+U8OmkY6KqM5O592Dp8HoHIvYyi0u7+afS6+Y/tns1sdB+1WXZeDi/KZ/dOkrCTvL8IzeEBdCkXkGxbzlWgaDbs32nqVaotNa0MvgVHBhizdn2O8lPGtVeAp0cA3n+0ArKqEjIFRYPNfG+GwpA8odJiFAi9Dzb0gRivmOfSdA8aFIRLSl9xI1PGsw7OW8LoXArwqEvITYrPk5kp6raASQPV6TG4VQ0wREY2tA2T4J3nOkY9Jks3hNOmUxelxC8e/RbL8+bie/RnSe/0ut9OXGKnilIOSwsbq0Og0m1J6mJIMIbt8w9zC02Bg0="
    project: "qa.ezbc.me"
    on:
      branch: "qa"
  - provider: firebase
    token:
      secure: "SzfombktJ+afoF5YEG+9P9pdEZ225kGfrucxO81X+iT+DjaewzxK7dekUpl6JByrUqtM/H2Tcj/+q3SbbuQBmtUZPU8s/gMmiJ5L8GeP4mgaIXot1OblNVGT/KecURaDb0HQW6yeO9bVCR9y6SXrW4onM2LWEWvu3kw8XYsGjI0/FivfHVZp7mY9bcbIpIWRF3oOdlvKzL6xkTSqt19Jip2BsLLmt7/ReCg3vz734dWppw2uBBxhAxiF5fEu50hSDkQbkGR2ejaoknWfzPteNvytmu47eTHwwLMx85cjRSG1fAPeMBHSb6ZsM+SqrCmfIg2NVn3YFr5XhAI54Fiz7tPSV4sdE3DYtMhWCE2TSfBDvKUZENPpkDk/3VSdJ7klwdF8SmVuwo7d10aCdkW1jG3CYKQZnXUgbFcYAN6mt6/rZz0iQIkPJh3zm6dvvZ4CSyLxJVpSnRtiu7qAiSP2k/2I2EuTAp7arPh4FGoLDzNz+cVBWCIP4YHbW5i7ouEvc9vx2O2EG1vbu25mPLBe9AWJW7galFcaBI+PaXZyL9feCCvxqPAJHdJFr1Qb3p9SP6fBz7qiqd25UjSduW5ew/4X4vHpmK1b5TF/XWo0yi5zUhTC0A8qqWlEQsk3xULfFolQ1FMzUxOiWJr0QYyf2A8EkvMXfgaQvjJh9nixHp8="
    project: "ezbc.me"
    on:
      branch: "master"
notifications:
  email:
    on_success: always
    on_failure: always
