sudo: false
language: ruby
rvm:
- 2.3.1
before_install:
  - export TRAVIS_BUILD_ENV="dev"
  - if [[ $TRAVIS_BRANCH = 'qa' ]]; then export TRAVIS_BUILD_ENV="qa"; fi
  - if [[ TRAVIS_BRANCH = 'master' ]]; then export TRAVIS_BUILD_ENV="prod"; fi
install:
- echo "$TRAVIS_BUILD_ENV"
- bundle install
- gem install jekyll
script:
- bundle exec jekyll build --config _config.yml,_config_"$TRAVIS_BUILD_ENV".yml
deploy:
  - provider: firebase
    token:
      secure: "R1/ZAxj+X350H0/ZeixqemIVo7RVI0La3+y40zM2OPhE3GT39/+JuK9o2o2HV/x8pHZnu74XhQcm3JOK9Lj0d/XW1/C8SBJeNYHgISmjV//fEUN5xeFlLfv5uFCYaZUgP5ZEMrl1OzHx3tL8S9Kdx5UcO1G3EFfx6r4XC8O92JDLpOxvecbohRP6oa+vdarAShyhIIYEe5A2zKbgXGzEjAgV8Xbe3nyswsYcbbUo2rethNQGTL+O+6vXVM+BPnAY6UKIX3tE+4gmuzWRCt57Qb4VhGWLHBCNP1B3IaZbRC/uCi/dYtnHdD9TlexZYQT+xkF8q2IOjH5cwJQLlVgAy5OfWpmYSyFT7f9T208o9S61GlQshcu+HWdGO7NLQWuvbfTFQyMugnQj3u1AZ+yO/JDBvM7jWX/eJFiSwhrkAuV7YOdy5hfIS2Y0x+r0pZV/l+0df9zc63BeLg9dP6HvSChkvHCVufyUbpm9XZwkEoXMxo+f+Wy8cEnQq5y8ZlZdLbYCCoF/7ZcBMJ9JCVoePSczRzD++qdhqCNhd8+Us9bagYAQXIrbKwnJqSSe4GFWcbViyGnOwXxnkVgb6OgiHtyMn7crC3wZt/+xZ2+QDnBD3D1R+eYreIKHJaBDDHWKZxRE6331Dz29rIY3EnZfB/+k0mubuNs792IyT+wsvuY="
    project: "dev.ezbc.me"
    on:
      condition: "$TRAVIS_BUILD_ENV=dev"
  - provider: firebase
    token:
      secure: "ZlPJxKk7T0OTVygtpNfn3Z6/E5NHfMNktoJCQdTwEiL0oKW6t9m/IFJLwonPPzljHwTdcmBC0ugebkEpCVmAhVg9859Jv6zUldr6BiWj5SP9Z39cQHx47a52n/1GQCh3tfD+MPVDeEeTi33sWVTnHnvhXfvxirw/jtVsa8iAutRWHJiMg74j9pGfGggPkMPPoItGpj3QUlUG/xNEpIBI7OdGc9Fr7+ARnpRuqoAeDCNx+rsaYtlAWvD2yyitNMvn3W+mHMJJ7WHnehmb5VfpmwFHDg1Eq+aLE2OEmFls6IxJ0cQWZ+HnJYPFE/cxlW3aBeyGyaO5AKeMkHgIWom4hZzT2Fuxkke7UMLe6HEOI7+DmVPfFK+U8OmkY6KqM5O592Dp8HoHIvYyi0u7+afS6+Y/tns1sdB+1WXZeDi/KZ/dOkrCTvL8IzeEBdCkXkGxbzlWgaDbs32nqVaotNa0MvgVHBhizdn2O8lPGtVeAp0cA3n+0ArKqEjIFRYPNfG+GwpA8odJiFAi9Dzb0gRivmOfSdA8aFIRLSl9xI1PGsw7OW8LoXArwqEvITYrPk5kp6raASQPV6TG4VQ0wREY2tA2T4J3nOkY9Jks3hNOmUxelxC8e/RbL8+bie/RnSe/0ut9OXGKnilIOSwsbq0Og0m1J6mJIMIbt8w9zC02Bg0="
    project: "qa.ezbc.me"
    on:
      branch: "qa"
  - provider: firebase
    token:
      secure: "SzfombktJ+afoF5YEG+9P9pdEZ225kGfrucxO81X+iT+DjaewzxK7dekUpl6JByrUqtM/H2Tcj/+q3SbbuQBmtUZPU8s/gMmiJ5L8GeP4mgaIXot1OblNVGT/KecURaDb0HQW6yeO9bVCR9y6SXrW4onM2LWEWvu3kw8XYsGjI0/FivfHVZp7mY9bcbIpIWRF3oOdlvKzL6xkTSqt19Jip2BsLLmt7/ReCg3vz734dWppw2uBBxhAxiF5fEu50hSDkQbkGR2ejaoknWfzPteNvytmu47eTHwwLMx85cjRSG1fAPeMBHSb6ZsM+SqrCmfIg2NVn3YFr5XhAI54Fiz7tPSV4sdE3DYtMhWCE2TSfBDvKUZENPpkDk/3VSdJ7klwdF8SmVuwo7d10aCdkW1jG3CYKQZnXUgbFcYAN6mt6/rZz0iQIkPJh3zm6dvvZ4CSyLxJVpSnRtiu7qAiSP2k/2I2EuTAp7arPh4FGoLDzNz+cVBWCIP4YHbW5i7ouEvc9vx2O2EG1vbu25mPLBe9AWJW7galFcaBI+PaXZyL9feCCvxqPAJHdJFr1Qb3p9SP6fBz7qiqd25UjSduW5ew/4X4vHpmK1b5TF/XWo0yi5zUhTC0A8qqWlEQsk3xULfFolQ1FMzUxOiWJr0QYyf2A8EkvMXfgaQvjJh9nixHp8="
    project: "ezbc.me"
    on:
      branch: "master"
notifications:
  email:
    on_success: always
    on_failure: always
