sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.1
branches:
  only:
    - master
    - develop
before_install:
  - export TRAVIS_BUILD_ENV="dev"
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then export TRAVIS_BUILD_ENV="prod"; fi
install:
- echo "$TRAVIS_BUILD_ENV"
- bundle install
- gem install jekyll
script:
- bundle exec jekyll build --config _config.yml,_config_"$TRAVIS_BUILD_ENV".yml
deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "Oj8qB13K4hdW1iojpOm7/+c2DJCDAEq+EzJUZgety//Viv4FichjMYy9Q2ioUI7mEAjFwYtE1gg0Al7p7yEoKOkKk+LRc5/NP2xNl/9kjV8I6nedpn5RWeCfzCMMQs4nN3OfehK9B2tNTBazqM2d2gDvRmgyxywdfF9JMCIHdFiJLBNeM74IgXF1xlUL76kNdgGcPCEC/RdahVcCKXrhstWp2QF4IDxzIvSQneTlDElD9ByRpoOa6smXnZcBDXLtesDMmaxgj3VRMx4AJdYFxxC+NUqDm8vGYO83KWkTHCqLSkx+10dyztqZIi8mm71GbB0V+YZTlYwMQd39aX7PITy0+BuN/Gol5rj6UhW571cf8Fzi4mRaCjUZmsjTFRTXttOiMcdkxsw8E3AF+Jhuugskw8WMiCbA/cb2Ae4vhJsNiTNUmCnN5IrOMlaDR+tj1CS+1qyKFy73Zq6Q3tn4aZsB4Vy5adEtqTR+pAyeT+1WVql1xmPoyEG7Gc+qI0wp6zz6bgRe2hiF65EBu7NuycsDkc75n0Y/pH2XLNbm7SdSgHC7Zuy+lA74YT8IqGR9b6afoC0vy/yS5kJ1ERwm3ZRQ7c1qNH/KGEkQzNkEviraoF34z6MluOocF6crO4mBELlS2uDH/V/VSThwsowsovtPaB30OzdhbDzOOrO3IIE="
    project: "devezbcme"
    on:
      branch: "develop"
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "dA4ZjQZD9aRfNKRGRxMJosBRIJ9bWHgHI/Mf53lbxKIZA9c8oMKQilDMwdLSiPt6uVkGcp4SIyQrOy/FdJgHA+Ho4KcxITcvGf4RPs+yfOFiYJWtYJ0W6dM+BV29heUBav18wCOh8DYEdZewRqT6QQc7YY4SDvK/3eWxzRHZUbTtFzbIqcfdOkHK7OC5Zem/D77spTvyg2E7+lqTyyMuxZam3tPMGd7ianGDEaKQcFEIVt95MiukmWhJ/qpymtJ1jKNF5qNHlM7w9qQZSE6VcZYWJq8Uc1Q5mhvCD3xcywZnrZxrCbZck1FDNQAYfDocKltXDmaNF620Bo8WgdOB1Vx+ldD3WapXUjeMkTFjf+P3WnDHSju52T+tZOTOsdXsexVljJcTSFrss1bDjGyM5yq1wH3IepZmAVHX5QqU4yCMgv9sYUweb4BA+1NB/n0KKMWdnfkMcaUt9j71YIDnJ+lZ8qMykoFVkHhmnlyJZKHoVa7uNpVvdk2IA+PtlLTxQND7YbswlB3h7eR08raOv1fohZ8WKe80+h5GcdaEu1AdUoS4be2XGLqZB9zsbfDWcD9I04zvVodXh418Va3Ub7wnpxAznWvSw6lfGckBtC5WdfY0ki/AmY1Yh7erfLrG+cTJsgdocBxDjcUjs8aJ383493seCJEOhB5yFPFaqFo="
    project: "prodezbcme"
    on:
      branch: "master"
notifications:
  email:
    on_success: always
    on_failure: always
after_success:
  - bash scripts/clearcache.sh -k "$CF_AUTH_KEY" -e "$CF_AUTH_EMAIL" -z "$CF_ZONE"

