sudo: false
language: ruby
rvm:
- 2.3.1
env:
- 
install:
- bundle install
- gem install jekyll
script:
- bundle exec jekyll build --config _config.yml
- firebase deploy
notifications:
  email:
    recipients:
    - $NOTIFICATION_EMAIL
    on_success: always
    on_failure: always
