name: Elijah's Webpage
description:  Blogs, astro, and more

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

permalink: /:year/:month/:day/:title/
owner:
    disqus_shortname: httpezbcme
    name: Elijah Bernstein-Cooper
    twitter: ebernste1
    github: ezbc
    bitbucket: ezbc
    googleplus: ElijahBernsteinCooper
    linkedin: ElijahBernsteinCooper

ga_id: ezbc
ga_username: ezbc

timezone: Central
