# General Settings
name: Elijah Bernstein-Cooper
job_title: Developer
email: ezbc@ezbc.me
description: Developer by day and hobbiest by night.
avatar: /media/avatar.jpg
favicon: /favicon.ico
analytics_code: UA-XXXXXXX-2
disqus: httpezbcme

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: '' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/elijahbernsteincooper/' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/ezbc' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 0
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: //localhost
baseurl:

# Includes
include: ["_pages"]

# Outputting
permalink: /:year/:month/:day/:title
category_dir: categories

# Pagination
pagination:
  enabled: true
  sort_reverse: true
  permalink: '/page/:num/'

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

keep_files: [media]

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

