version: '3'
services:
  jekyll:
    image: bretfisher/jekyll-serve
    command: /bin/sh -c "bundle exec jekyll serve --watch --force-polling --host=0.0.0.0 --incremental --config=_config_local.yml,_config.yml"
    ports:
      - 4000:4000
    volumes:
      - ./:/site
    working_dir: /site
